version: "3.8"

name: "moodle"

services:
  mariadb:
    container_name: moodle-mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    networks:
      - moodle_network
    volumes:
      - mariadb_data:/var/lib/mysql

  moodle:
    container_name: moodle
    image: bitnami/moodle:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_HOST: mariadb:3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      ALLOW_EMPTY_PASSWORD: "yes"
      MOODLE_URL: http://localhost:8080
    networks:
      - moodle_network
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata

networks:
  moodle_network:
    driver: bridge

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
